config/routes.rb
Coote::Application.routes.draw do

  get "top/index"
  match '/mono/new' => 'mono#new', :as => :new_mono
  match '/mono/create' => 'mono#create', :as => :create_mono
  match '/mono/delete' => 'mono#destroy', :as => :delete_mono
  match '/mono/:id/comment/new' => 'mono#new_comment', :as => :new_comment
  match '/mono/:id/comment/create' => 'mono#create_comment', :as => :create_comment

  root :to => "top#index"

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :name, :type => String
  field :body, :type => String
  embedded_in :mono

  validates :name, :presence => true
  validates :body, :presence => true
end

app/models/mono.rb
#coding: utf-8
class Mono
  include Mongoid::Document
  include Mongoid::Timestamps
  field :from, :type => String
  field :to, :type => String
  field :body, :type => String
  field :status, :type => Integer
  embeds_many :comments

  validates :body, :presence => true
  validates :status, :presence => true

  before_create :set_defaults_value

  STATUSES = [
    {:value => 0, :text => '買って'},
    {:value => 1, :text => '買ってくる'},
    {:value => 2, :text => '買ってきた'},
    {:value => 99, :text => 'ダメ'}
  ]

  def self.status_request
    Mono.status_value(0)
  end

  def self.status_will
    Mono.status_value(1)
  end

  def self.status_done
    Mono.status_value(2)
  end

  def self.status_deny
    Mono.status_value(3)
  end

  def self.status_request_text
    Mono.status_text(0)
  end

  def self.status_will_text
    Mono.status_text(1)
  end

  def self.status_done_text
    Mono.status_text(2)
  end

  def self.status_deny_text
    Mono.status_text(3)
  end

  protected
  def set_defaults_value
    if self.from.nil? || self.from == ""
      self.from = "Anonymous"
    end
    if self.to.nil? || self.to == ""
      self.to = "|:3ミ"
    end
  end

  private
  def self.status_value(index)
    STATUSES[index][:value]
  end

  def self.status_text(index)
    STATUSES[index][:text]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mono_controller.rb
class MonoController < ApplicationController
  def new
    @mono = Mono.new
  end

  def create
    @mono = Mono.new(params[:mono])
    @mono.status = 0
    if @mono.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    redirect_to root_path
  end

  def new_comment
    @comment = Comment.new
    render :layout => false
  end

  def create_comment
    @mono = Mono.find(params[:id])
    comment = Comment.new(params[:comment])
    @mono.comments << comment
    @mono.save
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @monos = Mono.order_by(:created_at.desc).paginate(:page => params[:page], :per_page => 5)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def hbr(str)
    h(str).gsub(/\r\n|\r|\n/, "<br />\n")
  end
end

app/helpers/mono_helper.rb
module MonoHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/_footer.html.haml
%footer#contentinfo.body.transform_content_before
  %address#about.body
    %span.primary
      %strong
        = link_to "coote", "/", :class => ["fn", "url"]
    %span.bio
      は事務のお姉さんに「便所の消臭スプレー買うてきて！」と言うためのWebサービスです
      %br/
      cooteを使ってあんなスプレーやこんなスプレーを買ってもらいましょう
      %br/
      ソースコード >>>&nbsp;
      = link_to "github", "https://github.com/bugcloud/coote", :target => "_blank"

app/views/layouts/_header.html.haml
%header#banner.body
  %h1
    = link_to "coote", root_path
  %nav
    %ul
      %li{:class => (request.path_info =~ /^#{root_path}$/ or request.path_info =~ /\/top\/index/ )? 'active' : ''}
        = link_to "Home", root_path
      %li{:class => (request.path_info == new_mono_path)? 'active' : ''}
        = link_to "New coote", new_mono_path
      %li#about
        = link_to "About", "#aboutCoote"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Coote
    = stylesheet_link_tag %w(scaffold default all)
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    = render 'layouts/header'
    %section#content.body
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
      = yield 
    =render 'layouts/footer'

app/views/mono/create_comment.js.haml
- if @mono.errors.any?
  alert("入力して");
- else
  window.location.replace("/");

app/views/mono/new.html.haml
- if @mono.errors.any?
  #error_explanation
    %ul
      - @mono.errors.full_messages.each do |msg|
        %li= msg
= form_for @mono, :url => '/mono/create' do |f|
  =f.text_field :from, :placeholder => '私は'
  %span は
  =f.text_field :to, :placeholder => '○○さん'
  %span に
  %div &nbsp;
  =f.text_area :body, :size => '50x4', :placeholder => '☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻'
  %br/
  %div &nbsp;
  %span を
  =f.submit "こーてほしい"

app/views/mono/new_comment.html.haml
.triangle-border.right
  = form_for @comment, :url => create_comment_path(@coote_id), :remote => true do |f|
    = f.text_field :name, :placeholder => "Who are you?"
    %br/
    = f.text_area :body, :placeholder => "Comment here..", :size => "50x5"
    %br/
    = f.submit "comment"

app/views/top/index.html.haml
- @monos.each do |m|
  .coote_request
    %p
      %strong=m.from
      &nbsp;says to&nbsp;
      %strong=m.to
      .triangle-border.top
        #{hbr m.body}こーてきて！
      .clearfix
        %div.comments_area{:id => "comments_area_#{m.id}"}
          - m.comments.each do |c|
            .triangle-border.right
              #{hbr c.body}
              %p.speecher
                %strong=c.name
      %p.clearfix
        = link_to "reply", "#", :id => "reply_to_#{m.id}", :class => "reply_link", "data-mono-id" => m.id
.clearfix
  = will_paginate @monos